### PR TITLE
fix: merge service crate

### LINKED ISSUE #411: Merge service crate into vault
It is only ever consumed by the Vault binary so it doesn't make sense to keep separate. Also if / when we merge this we can combine the `Error` types for some simplification (discussed [here](https://github.com/interlay/interbtc-clients/pull/394#issuecomment-1307235403)).

Possibly related: https://github.com/interlay/interbtc-clients/issues/407

### PR DESCRIPTION
**Pull request by nakul1010**
Closes #411 
The PR adds the following
- [x] removes service crate
- [x] merge error types
- [x] duplicate required dependencies of the service crate in the faucet crate.

### CODE REVIEW

File: vault/src/error.rs [hunk 1]
```diff
@@ -46,7 +46,7 @@ pub enum Error {
     BroadcastStreamRecvError(#[from] BroadcastStreamRecvError),
 }
 
-impl From<Error> for service::Error<Error> {
+impl From<Error> for crate::services::Error<Error> {
```
[the remark this answers is not in the document]
Comment (nakul1010) [reply vault/src/error.rs]: Done

File: vault/src/connection_manger.rs [hunk 2]
```diff
@@ -138,18 +134,17 @@ impl<Config: Clone + Send + 'static, F: Fn()> ConnectionManager<Config, F> {
...
-                }
-                Err(err) => {
-                    tracing::warn!("Disconnected: {}", err);
-                }
-                _ => {
-                    tracing::warn!("Disconnected");
+
+            let backoff = ExponentialBackoff::default();
+
+            backoff::future::retry(backoff, || async {
```
Comment (gregdhill) [inline vault/src/connection_manger.rs:140]: I don't think we should be using backoff here, this whole method is anyway wrapped in a loop with failure handling below based on the `RestartPolicy`.

Comment (nakul1010) [reply vault/src/connection_manger.rs:140]: so should I just break the loop and return in case of `backoff::Error::Permanent` and other errors will be logged, OR  create a new Error type `ServiceError` which will be used by the `Service` trait in which `Permanent` error will be returned. 

```Rust
pub enum ServiceError {
      Permanent<crate::Error>,
      Transient<crate::Error>
}
```

Comment (gregdhill) [reply vault/src/connection_manger.rs:140]: Don't break the loop since we have shutdown handling below. How did we handle the `Abort` and `Retry` variants before?

Comment (nakul1010) [reply vault/src/connection_manger.rs:140]: In case of abort returning an error [here](https://github.com/interlay/interbtc-clients/blob/eeb2fda6d584dbf851ad851dc013e3cf52463de4/service/src/lib.rs#L144)

Comment (gregdhill) [reply vault/src/connection_manger.rs:140]: So I think the idea was just to replace `Abort` with `Permanent` and `Retry` with `Transient` and then keep our logic the same.

File: vault/src/system.rs [hunk 3]
```diff
@@ -584,9 +581,11 @@ impl VaultService {
         Ok(())
     }
 
-    async fn run_service(&self) -> Result<(), ServiceError<Error>> {
-        self.validate_bitcoin_network().await.map_err(ServiceError::Abort)?;
-
+    async fn run_service(&self) -> Result<(), BackoffError<Error>> {
+        //ToDo: remove service error put all errors in error
```
Comment (gregdhill) [inline vault/src/system.rs:585]: Remove

File: vault/src/system.rs [hunk 4]
```diff
@@ -596,18 +595,21 @@ impl VaultService {
...
         }
 
         let num_confirmations = match self.config.btc_confirmations {
             Some(x) => x,
-            None => self.btc_parachain.get_bitcoin_confirmations().await?,
+            None => self
+                .btc_parachain
+                .get_bitcoin_confirmations()
+                .await
+                .map_err(|err| BackoffError::Transient::<Error>(err.into()))?,
```
Comment (gregdhill) [inline vault/src/system.rs:612]: I think before we automatically cast to `Retry`, is this no longer the case (for `Transient`)?

File: vault/src/error.rs [hunk 5]
```diff
@@ -44,10 +44,29 @@ pub enum Error {
...
+    ParseIntError(#[from] ParseIntError),
+    #[error("TokioError: {0}")]
+    TokioError(#[from] TokioJoinError),
+    #[error("System I/O error: {0}")]
+    IoError(#[from] IoError),
 }
 
-impl From<Error> for service::Error<Error> {
-    fn from(err: Error) -> Self {
-        Self::Retry(err)
```
Comment (gregdhill) [inline vault/src/error.rs:51]: This is where we defaulted to `Retry`, is it possible to keep this for `Transient`?

**Review by gregdhill — COMMENTED** [review]
Looks good, couple minor comments to resolve and then this will be g2g!

File: vault/src/system.rs (hunk 4 above)
Comment (nakul1010) [reply vault/src/system.rs]: The error returned by the `get_bitcoin_confirmations` method is `RuntimeError` and not `crate::Error`, hence I need to explicitly convert it. In the recent commit, I have just mapped it to `crate::Error` instead of `backoff:Error`. There is already `from` trait implemented in backoff::Error, check it out [here](https://docs.rs/backoff/latest/src/backoff/error.rs.html#110)

File: vault/src/error.rs (hunk 5 above)
Comment (nakul1010) [reply vault/src/error.rs:51]: The above comment covers the solution, as the `From` trait for `Transient` error has already been implemented by the `backoff::Error` type.

Comment (gregdhill) [reply vault/src/error.rs:51]: We need to default to `Transient` somehow, can you investigate how to do that?

**Review by gregdhill — APPROVED** [review]
